baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Kafka EngDoc'

theme = 'hextra-main'

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule

[params]
title = "Kafka Engdoc"
author = "By Team Messaging Platform"
description = "Kafka Documentation Page"
profilePicture = "/images/Kafka.jpg"
readMore = true
#contactFormAction = "https://formspree.io/f/your-form-hash-here"

[author]
  name = "Linh"

defaultContentLanguage = "en"

[languages]
  [languages.en]
  languageName = "English"
  weight = 1
  title = "Hextra"

  [languages.ja]
  languageName = "日本語"
  weight = 2
  title = "Hextra テーマ"

  [languages.zh-cn]
  languageName = "简体中文"
  languageCode = "zh-CN"
  weight = 3
  title = "Hextra"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Documentation"
  weight = 150
  identifier = "documentation"
  url = "/docs/"

  [[menu.main]]
  name = "Blog"
  weight = 300
  identifier = "blog"
  url = "/blog/"
